### ISSUE TITLE
Streaming possible?

### ISSUE THREAD

**Issue by arve0** [halset/jsosi#4]
Hi and thanks for the lib!
I have a dataset which is ~2GB. It takes about 45 seconds to load on my dev machine:

```scala
val file = new java.io.File("/Users/arve/Downloads/Basisdata_0000_Norge_25833_Stedsnavn_SOSI.sos")

println(new Date() + " has file: " + file.exists())

// this step takes 45 seconds
val reader = new SosiReader(file)
println(new Date() + " SOSI file loaded")

val feature = reader.nextFeature()
println(new Date() + " first feature id: " + feature.getId())
```

I see that the code reads through the file three times,

1. assure correct character set ([SosiReader line 123](https://github.com/halset/jsosi/blob/master/src/main/java/no/jsosi/SosiReader.java#L123))
2. index it ([SosiReader line 89](https://github.com/halset/jsosi/blob/master/src/main/java/no/jsosi/SosiReader.java#L89))
3. read for real ([SosiReader line 178](https://github.com/halset/jsosi/blob/master/src/main/java/no/jsosi/SosiReader.java#L178)) - does actually not read until one calls `nextFeature` 

Here is a comment before the [indexing in the code](https://github.com/halset/jsosi/blob/master/src/main/java/no/jsosi/SosiReader.java#L87): _need to parse all features as FLATE can reference KURVE later in the file_

Does this mean that a streaming parser is impossible (or hard) to implement?

**Comment by halset** [comment]
@arve0 The references are not all backwards, so I think it is not possible to stream it. The extra read for charater sets should not be needed, but I have seen some SOSI files with character set in the header that does not match with the actual character set used in the file.

If you find a better and still robust way to stream, please let me know!
